project_id = "pudsfdinvcmekplianuf"

[functions.plagiarism-check]
verify_jwt = false

[functions.run-code]
verify_jwt = false

[functions.analyze-submission]
verify_jwt = false

[functions.seed-users]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
